name: UltimateMobCoins
main: nl.chimpgamer.ultimatemobcoins.paper.UltimateMobCoinsPlugin
version: ${version}
description: UltimateMobCoins plugin
api-version: '1.19'

softdepend:
  - PlaceholderAPI
  - MythicMobs
  - Vault
  - Oraxen
  - ItemsAdder
  - EcoMobs
  - BetonQuest
  - WorldGuard
  - MiniPlaceholders
  - RoseStacker